### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dannyodare** [WojciechKrysiak/SCModManager#1]
Hi,

Apologies for being stupid, but how do I use this mod? I've got no idea! 

Thanks,
DANNY

**Comment by WojciechKrysiak** [comment]
Hi Danny,

It's not really a mod, it's a very simple mod conflict checker. When opened
it should list all your installed mods and tell you which ones have
conflicts (i.e. affect the same file).

**Comment by 09williamsad** [comment]
Does it have to be placed in the games directory or the location of mods?
When I launch it all i get is an error in the log file and the process taking up around 1.5GB of memory without seeming to do anything.

Here is the log file:
[log.txt](https://github.com/WojciechKrysiak/SCModManager/files/546306/log.txt)

**Comment by WojciechKrysiak** [comment]
Hi,

It runs from anywhere. As to the crash - the cause is having too many mods installed (the tool preloads everything, including images). Additionally, Heinlein seems to have changed the way the mods are references. In your Documents/Paradox Interactive/Stellaris/Mods folder there should be two sets of .mod files - one starting with ugc, one without. The one without ugc should be safe to remove, and this should help with this crash.

**Comment by 09williamsad** [comment]
All of my mods have ugc but I found that just waiting longer resolved the issue.

**Comment by boycad** [comment]
I also need simple instructions.  Extract->then launch... which file will launch the manager?

**Comment by WojciechKrysiak** [comment]
If you downloaded the files through git-hub, you will need to compile them
manually using visual studio (a free version is available from microsoft)

if you've downloaded it from the stellaris modding forum, then simply run
the .exe file from the folder you've extracted it to.

**Comment by boycad** [comment]
Well I learned something right there, about compiling.  But, yes, could we have a download link for the .exe, please?  I canna find a ting, cap'n.

**Comment by WojciechKrysiak** [comment]
It turns out I did some releasing on github as well (didn't work on it for
a while) - https://github.com/WojciechKrysiak/SCModManager/releases

**Comment by dannyodare** [comment]
Yes, please give us a link to the Stellaris Mod Manager exe - as I'm
completely unable to find it as well.

Thanks,
DANNY

**Comment by Marcomorachi** [comment]
no exe file to use
