### ISSUE TITLE
Can't start the program

### ISSUE THREAD

**Issue by DanTheAMan** [WojciechKrysiak/SCModManager#10]
So, weird bug. Every time I try to run the .exe the file disappears by itself. It runs for like 10-15 seconds then it shuts down. When I try to extract the files again it requires administrative permission (which I grant), but apparently it doesn't go through and the WinRAR Diagnostic just says "Access Denied" (snapshot for reference)
![wat](https://user-images.githubusercontent.com/34393504/33794662-b4e77f5e-dcd8-11e7-9d3f-bca8ec8825f0.JPG)

**Comment by WojciechKrysiak** [comment]
This looks like an issue with your antivirus software. I assume it's
killing the process and deleting the .exe.

I've run the file through an online virus scanner, and it's not showing any
problems. Can you tell me what antivirus you're running?

**Comment by DanTheAMan** [comment]
BitDefender and Malwarebytes, and you were right, it was BitDefender that was causing the problem, yet it didn't alert me about any harmful program when it was deleting the .exe (it was also quite heavy on my CPU when I opened the .exe, dunno why I haven't thought about this possibility before I posted). 

Thank you very much. You have a very nice mod manager here, keep it up

**Comment by WojciechKrysiak** [comment]
Thanks for the update, and the kind words!
