### ISSUE TITLE
White screen on game load

### ISSUE THREAD

**Issue by CrimsonShrike** [WojciechKrysiak/SCModManager#13]
Had this issue with previous releases too, after running exe, saving mods I choose and running stellaris and load screen finishing, I am greeted by an entirely white screen.

Deleting stellaris folder fixes this.

edit: Windows 10 to clarify.
edit2: Tracked issue to settings file, values are set as 10000000 instead of 10.00000 for example. Maybe important?

**Comment by WojciechKrysiak** [comment]
Thanks for the update - the 10.00000 to 10000000 is an important clue. 

What is your native decimal separator format? And could you upload your settings.txt file and the one stellaris creates by default?

**Comment by WojciechKrysiak** [comment]
Potentially fixed - confirm if you can.

**Comment by CrimsonShrike** [comment]
Missed the email notifications, will test tomorrow if I can.

**Comment by CrimsonShrike** [comment]
seems to work properly now

**Comment by WojciechKrysiak** [comment]
Thanks for testing it out!
