### ISSUE TITLE
Issues with merging

### ISSUE THREAD

**Issue by Midaychi** [WojciechKrysiak/SCModManager#17]
With 6.0.2, many English localization files are empty and some common files aren't read correctly either (example, xeno trait mod, traits show up as their bare strings with bare description string and no modifiers). With 6.0.1, they are not empty but something is still malfunctioning. (Ie: they are named their bare string and have bare description strings but their modifiers show up).

The localization files are converted from dos line endings to unix endings in 6.0.1, but batch converting them back to dos doesn't seem to fix anything. Other than that, I can't tell what the difference is that's causing this.

**Comment by WojciechKrysiak** [comment]
In 6.1 they weren't being saved with the correct Unicode BOM, see #16. I'll try to re-fix that issue ASAP

**Comment by Midaychi** [comment]
I've also noticed that "Picking right" or "Picking left" acts as if the file conflict has been resolved but when you save the merge, only an empty file version of it appended .mzip is created.

Since it thinks the conflict is resolved, you instantly get deselected from the conflict and are unable to select it again and have no option to press 'save' at any point.

**Comment by Midaychi** [comment]
also while examining file conflicts in merge, sometimes the "right file" or "left file" are displaying the wrong mod for the conflict and trying to use the dropdown box shows the correct mod, but selecting that or the blank sometimes crashes the program.

**Comment by Midaychi** [comment]
Also, selecting "left as file before" or after or right as file before or after when there are multiple conflicts over the same file sometimes crashes the program, or otherwise severely impacts performance.

**Comment by Midaychi** [comment]
Left as file or right as file before or after ALSO result in an empty .mzip file

**Comment by Midaychi** [comment]
Also when there are an odd number of conflicts, and you finish merging left or right, a conflict entry of that file will still exist in the list as a red entry but is non selectable and has "1" next to it.
