### ISSUE TITLE
How to compile from source?

### ISSUE THREAD

**Issue by ruifung** [WojciechKrysiak/SCModManager#26]
It's quite difficult to compile this from source, especially as it seems to be missing several things not limited to CWTools, and some Avalonia. I've been trying to compile a version that includes the fixes from #23 

Any assistance would be appreciated.

**Comment by WojciechKrysiak** [comment]
Please provide the errors you are getting. There is a CI build running on [AppVeyor](https://ci.appveyor.com/project/WojciechKrysiak/scmodmanager/history) and it's green, so I didn't really expect any issues for source builds.

**Comment by ruifung** [comment]
Huh. Thanks for the CI link. It was probably my environment isn't set up to compile this properly, got a bunch of library version mismatches all over the place between nuget versions and required versions.

Probably should put the .NET framework version requirements in the readme and maybe a link to the CI page too.
