### ISSUE TITLE
Updating the selected mods through the Stellaris Launcher doesn't update the selection with the mod manager

### ISSUE THREAD

**Issue by EnderShadow** [WojciechKrysiak/SCModManager#3]
A simple fix to this would be to read from the settings file every time you start the mod manager to get the latest mod list

**Comment by WojciechKrysiak** [comment]
It should actually be doing that already. I'll take a look when I have some time to see how it can be failing.

**Comment by TheBoboNL** [comment]
It could be that if you change the mods in the stellaris launcher, but do not launch the game, than the last_mods it not updated in settings.txt
