### ISSUE TITLE
Saving doesn't appear

### ISSUE THREAD

**Issue by Skukkuk** [WojciechKrysiak/SCModManager#4]
Hey Wojciech,

started latest build SCModManager.exe (only worked as admin for me). Then I tried to merge my actual used mods into a single mod-file. Resolved all issues, but the 'save' button is still greyed out. 

Any hint how to solve?

My idea is to create a single MP-mod-file for my companions to avoid managing 30-40 different mods for a single game session. 

Cheers,

Skukk

**Comment by WojciechKrysiak** [comment]
The only reason that the save button would be disabled is that there still
are some unresolved files.

Is the file list empty, when you check "show only conflicts"?

**Comment by Skukkuk** [comment]
Yeah. There is nothing more to solve. That's why I'm asking for assistance. 

BTW, can I save the merged mods into a single file to share with my MP buddies?

**Comment by WojciechKrysiak** [comment]
If the list is empty, you could try unchecking the checkbox and looking
through the full list manually, to see if the error is in the list collapse
logic, or in the button enable code.

As for your second question - the program outputs the merged mod into a
directory, do you could either zip it, and have your friends unzip the mod
as is (remember the .mod file). Or you could zip it (don't know if the
settings from https://stellaris.paradoxwikis.com/Save-game_editing are
required), modify the mod file to point to a zip, instead of a directory
and skip the unzip step for other users.

**Comment by Skukkuk** [comment]
#1 - Well, I did both. Check and uncheck. No change.
I solved all un-collapsed issues by choice (right/left) or save button. 

#2 - Am I questioned where to save the merged mod file? Probably I already saved by above saving-choice...where should the file be saved usually?

**Comment by WojciechKrysiak** [comment]
#1 seems there's a bigger problem. Unfortunately you might have to try
again.
#2 you can name your mod, but it's saved into the Stellaris mod directory
in  MyDocuments folder.

**Comment by Skukkuk** [comment]
Ok, thx for the information. 

When do you plan for a new version that is covering the # 1 problem?

**Comment by WojciechKrysiak** [comment]
If time permits, I'll take a look at it this weekend, but I can't promise
anything, as I assumed this already worked.

**Comment by Skukkuk** [comment]
NP, thx for taking the time to look into.

**Comment by Lofwyrger** [comment]
Have the same problem, checked the complet list and found a few entrys with a 0 behind them.

**Comment by Lofwyrger** [comment]
Did a little more testing. For Example, Mod [Ship Power Stations](http://steamcommunity.com/sharedfiles/filedetails/?id=776095610) and [Spaceport](http://steamcommunity.com/sharedfiles/filedetails/?id=965209251) are detected as conflicting. But in preview conflicts are no conflicts shown, also if i try to merge them, no conflicting files are shown.
Hope that helps to narrow it down.

**Comment by WojciechKrysiak** [comment]
Thanks for the report. This gives me a starting point for pinpointing the
issue. I'll let you know as soon as I have something.

**Comment by WojciechKrysiak** [comment]
Pushed a fix to resolve a stupid bug with the directory view window. This should now let you find the conflicts that were hidden previously.
