### ISSUE TITLE
mod "traditional trees" not registering

### ISSUE THREAD

**Issue by tekker2234** [WojciechKrysiak/SCModManager#40]
thane stus' mod called "traditional trees" which basically unifies and overhauls the traditions page around the mods "plentiful traditions" and "expanded stellaris traditions" is not being detected/showing up.
![traditional trees not showing up](https://user-images.githubusercontent.com/16428350/69887792-b946e380-12b6-11ea-8c21-8beabfa179b6.png)

**Comment by ghost** [comment]
Found the cause and fix for it.

Cause: traditional trees and some other mods using
version="2.X.*"
only instead of
supported_version="2.X.*"

while this launcher detect only supported_version="2.X.*"

adding
supported_version="2.5.*"
will fix it.

**Comment by matshou** [comment]
The mod will also not register if the `supported_version` tag is missing. 
Example: [Real Space - Colour Out of Deep](https://steamcommunity.com/sharedfiles/filedetails/?id=1918281610).
