### ISSUE TITLE
White listing certain neutral mod file

### ISSUE THREAD

**Issue by TheBoboNL** [WojciechKrysiak/SCModManager#9]
[Based of this reddit comment:](https://www.reddit.com/r/Stellaris/comments/7i1t6z/stellaris_mod_manager_tool_to_identify_and_fix/dqx5rnl/)
White listing certain mod files to prevent false positives on detecting conflicts;

- description.txt
- modinfo.lua

**Comment by WojciechKrysiak** [comment]
Added preferences to handle customizing the white list.
